### ISSUE TITLE
Marple installation failed with errors in python version

### ISSUE THREAD

**Issue by sattishv** [ensoft/marple#4]
Team
Marple installation failed with the below listed error. Error traces show issues with python3 should i use python2.7

Downloading/unpacking marple
  Could not find a version that satisfies the requirement marple (from versions: 0.1.dev1)
Cleaning up...
No distributions matching the version for marple
Storing debug log for failure in /home/sattivasudevan/.pip/pip.log

extract from pip.log

------------------------------------------------------------
/usr/bin/pip run on Wed Jan  2 06:20:16 2019
Downloading/unpacking marple
  Getting page https://pypi.python.org/simple/marple/
  URLs to search for versions for marple:
  * https://pypi.python.org/simple/marple/
  Analyzing links from page https://pypi.org/simple/marple/
    Skipping https://files.pythonhosted.org/packages/49/2f/9134c0e61fa884870f68bb21e053448bdc1cb8c66293eb3485c5e0318fd9/marple-0.1.dev1-py3-none-any.whl#sha256=3a9c87d927bfff9cc7d4d4c532135f097a46d455c88ea43552099d468b5f37f3 (from https://pypi.org/simple/marple/) because it is not compatible with this Python
    Found link https://files.pythonhosted.org/packages/6c/9a/f49797f56d6e83e605b7bc0accd1fb6fadbf674d69fe99553c37244f2b4f/marple-0.1.dev1.tar.gz#sha256=efd68a990fb86f33be1dc0622a996a6c1fc307b4019cbd2d8f84dd07badd3d86 (from https://pypi.org/simple/marple/), version: 0.1.dev1
  Ignoring link https://files.pythonhosted.org/packages/6c/9a/f49797f56d6e83e605b7bc0accd1fb6fadbf674d69fe99553c37244f2b4f/marple-0.1.dev1.tar.gz#sha256=efd68a990fb86f33be1dc0622a996a6c1fc307b4019cbd2d8f84dd07badd3d86 (from https://pypi.org/simple/marple/), version 0.1.dev1 is a pre-release (use --pre to allow).
  Could not find a version that satisfies the requirement marple (from versions: 0.1.dev1)
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
No distributions matching the version for marple
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 322, in find_requirement
    raise DistributionNotFound('No distributions matching the version for %s' % req)
DistributionNotFound: No distributions matching the version for marple

Thanks
Sattish.

**Comment by mattjware** [comment]
Hi Sattish,

From the Exception information it looks like your /usr/bin/pip points to python2.7, rather than python3:
File "/usr/lib/**python2.7**/dist-packages/pip/basecommand.py", line 122, in main

If you use a python 3 pip, this should work. Let us know if you still have problems.

Thanks,
Matt

**Comment by sattishv** [comment]
Thanks Matt will try with python3 and update the thread

**Comment by mattjware** [comment]
Hi Sattish,

Did it work with Python3? If so, the issue can be closed.

Cheers,
Matt

**Comment by sattishv** [comment]
Hi Matt,

It didnt work with python3. I have python -V 3.4.3

Have attached the output 

sudo python3 -m pip install marple
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
The directory '/home//.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting marple
  Could not find a version that satisfies the requirement marple (from versions: )
No matching distribution found for marple
~# python3 -V
Python 3.4.3
~#  python3 -m pip install marple
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
The directory '/home//.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home//.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting marple
  Could not find a version that satisfies the requirement marple (from versions: )
No matching distribution found for marple

Thanks
Sattish
